# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWork Api' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork Api
	pod 'Alamofire', '~> 4.9.1'
	pod 'SwiftyJSON'                                                                                                                  
	pod 'Toast-Swift'
  pod 'Kingfisher', '~> 7.0'
end
